#!/bin/bash
OUTPUT_DIR=${HOME}/.narou/output
MYBOOKS_DIR=${HOME}/.narou/mybooks
if ! [ -d ${OUTPUT_DIR} ]; then mkdir -p ${OUTPUT_DIR}; fi
if ! [ -d ${MYBOOKS_DIR} ]; then mkdir -p ${MYBOOKS_DIR}; fi
docker run -v ${MYBOOKS_DIR}:/opt/mybooks -v ${OUTPUT_DIR}:/opt/output -it amitsuka/narourb-docker narou $@
